# Generated by Django 3.1.3 on 2020-11-15 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 15, 7, 20, 18, 400398)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
